name: 'Sync'
description: ' Sync the local build folder with the S3CloudFront instance'
inputs:
  local_build_dir:
    description: 'Local build directory.'
    required: true
  aws_region:
    required: true
  aws_access_key_id:
    required: true
  aws_secret_access_key:
    required: true
  s3_uri:
    description: 'S3 URI to sync build directory with.'
    required: true
  cloudfront_distribution_id:
    description: 'CloudFront distribution ID.'
    required: true

runs:
using: 'composite'
steps:
  - id: process
    name: Process inputs
    shell: bash
    run: |
      "${{ github.action_path }}"/sync.sh
    env:
      AWS_DEFAULT_REGION: ${{ inputs.aws_region }}
      AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
      DIST_DIR: ${{ inputs.dist_dir }}
      S3_URI: ${{ inputs.s3_uri }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ inputs.cloudfront_distribution_id }}
