#!/bin/bash

source "$(dirname "$0")"/../common.sh

NORMALIZED_BRANCH_NAME=$(normalizeBranchName "$INPUT_BRANCH_NAME")
HEAD_SHORT_REV=$(git rev-parse --short HEAD)
BUILD_DIR_NAME=$NORMALIZED_BRANCH_NAME-$HEAD_SHORT_REV

echo "BUILD_DIR_NAME=$BUILD_DIR_NAME"
echo "REMOTE_BUILD_DIR=$INPUT_BASE_BUILD_DIR/revs/$BUILD_DIR_NAME"
echo "LATEST_BUILD_SYMLINK_PATH=../revs/$BUILD_DIR_NAME"
echo "REMOTE_LATEST_BUILD_SYMLINK=$INPUT_BASE_BUILD_DIR/branches/$NORMALIZED_BRANCH_NAME"
